# Generated by Django 3.0.5 on 2020-04-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial_defaults = [
        {
            "id": 1,
            "artist": "Van Halen",
            "title": "Best of Both Worlds",
            "album": "5150",
            "year": "1986"
        },
        {
            "id": 2,
            "title": "Takin' Care of Business",
            "artist": "BTO",
            "album": "Bachman–Turner Overdrive II",
            "year": "1973"
        },
        {
            "id": 3,
            "title": "Best of Both Worlds",
            "artist": "Van Halen",
            "album": "Best of Both Worlds",
            "year": "2004"
        }  
    ]

    def insert_defaults(apps, schema_editor):
        Song = apps.get_model('songs', 'Song')
        for row in Migration.initial_defaults:
            song = Song(**row)
            song.save()

    def remove_defaults(apps, schema_editor):
        Song = apps.get_model('songs', 'Song')
        for row in Migration.initial_defaults:
            song = Song(**row)
            song.delete()

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_defaults, remove_defaults)
    ]
